#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = Ildaeil

# --------------------------------------------------------------
# Do some magic

STANDALONE = true
include ../Common/Makefile.mk
