#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = Ildaeil-MIDI

# --------------------------------------------------------------
# Do some magic

include ../Common/Makefile.mk
