name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
env:
  CACHE_VERSION: 1
  DEBIAN_FRONTEND: noninteractive
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  win32:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/PawPawBuilds
          key: win32-v${{ env.CACHE_VERSION }}
      - name: Fix GitHub's mess
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update -qq
          sudo apt-get install -yqq --allow-downgrades libpcre2-8-0/focal libpcre2-16-0/focal libpcre2-32-0/focal libpcre2-posix2/focal
          sudo apt-get purge -yqq libnginx*
      - name: Set up dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -qq
          sudo apt-get install -y binutils-mingw-w64-i686 g++-mingw-w64-i686 mingw-w64 libsane:i386 libgd3:i386 libgphoto2-6:i386 libwine:i386 wine32:i386 wine-stable:i386
      - name: Build extra dependencies
        run: |
          git clone --depth=1 https://github.com/DISTRHO/PawPaw.git
          ./PawPaw/bootstrap-cardinal.sh win32
      - name: Build win32 cross-compiled
        run: |
          pushd PawPaw; source local.env win32; popd
          make features
          make NOOPT=true WITH_LTO=true -j $(nproc)
      - name: Set sha8
        id: slug
        run: echo "::set-output name=sha8::$(echo ${{ github.sha }} | cut -c1-8)"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-win32-${{ github.event.pull_request.number || steps.slug.outputs.sha8 }}
          path: |
            bin/*
            !bin/*-ladspa.dll
            !bin/*-dssi.dll

  win64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: |
            ~/PawPawBuilds
          key: win64-v${{ env.CACHE_VERSION }}
      - name: Fix GitHub's mess
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update -qq
          sudo apt-get install -yqq --allow-downgrades libpcre2-8-0/focal libpcre2-16-0/focal libpcre2-32-0/focal libpcre2-posix2/focal
          sudo apt-get purge -yqq libnginx*
      - name: Set up dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -qq
          sudo apt-get install -y binutils-mingw-w64-x86-64 g++-mingw-w64-x86-64 mingw-w64 libgd3:i386 libsane:i386 libgphoto2-6:i386 libwine:i386 wine32:i386 wine64 wine-stable
      - name: Build extra dependencies
        run: |
          git clone --depth=1 https://github.com/DISTRHO/PawPaw.git
          ./PawPaw/bootstrap-cardinal.sh win64
      - name: Build win64 cross-compiled
        run: |
          pushd PawPaw; source local.env win64; popd
          make features
          make NOOPT=true WITH_LTO=true -j $(nproc)
      - name: Set sha8
        id: slug
        run: echo "::set-output name=sha8::$(echo ${{ github.sha }} | cut -c1-8)"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-win64-${{ github.event.pull_request.number || steps.slug.outputs.sha8 }}
          path: |
            bin/*
            !bin/*-ladspa.dll
            !bin/*-dssi.dll
